### ISSUE TITLE
Keeps generating same tokens

### ISSUE THREAD

**Issue by Shell1010** [wodxgod/Discord-Token-Grabber#13]
Hi so whenever I run this program it keeps generating the same tokens over and over again? Is there any fix for this? I have added multiple different people into my server and it keeps generating the same two tokens.

**Comment by Ly0kha** [comment]
4.Send the script to your victim and make them run it.

**Comment by stupid-melon** [comment]
The token resets when:
1) Discord automatically changes the token once in a while for security purposes

OR

2) You change certain account details, such as your password, your email, etc

Till then, the token will remain the same and you can use it to login through whomever's token you have grabbed
