### ISSUE TITLE
Worked, and then stopped.

### ISSUE THREAD

**Issue by xsCalamity** [wodxgod/Discord-Token-Grabber#26]
I've used it around 20 times normally, I stopped for a bit to go do other things, and suddenly it doesn't work anymore. None of the webhooks I tried, on different accounts, etc., didn't work. No errors either.

**Comment by JoepTM** [comment]
Maybe discord patched it, idk. Since it's open source

**Comment by vyxzy** [comment]
> I've used it around 20 times normally, I stopped for a bit to go do other things, and suddenly it doesn't work anymore. None of the webhooks I tried, on different accounts, etc., didn't work. No errors either.

you got discord? i want to talk with you about this grabber
