### ISSUE TITLE
/

### ISSUE THREAD

**Issue by GamerLu911** [wodxgod/Discord-Token-Grabber#48]
Hi, is in this file a Virus? Or is this a mistake?
![image](https://user-images.githubusercontent.com/84204810/118323306-b4084380-b500-11eb-9dd5-72804a39527c.png)

**Comment by NotSwaraj** [comment]
Oh god, just please, don't use this, your too dumb for it. It's not a virus.

**Comment by msesjrl** [comment]
> Oh god, just please, don't use this, your too dumb for it. It's not a virus.

Agreed, if you have to ask this question you're 100% a script kiddie. If you understand code you will be able to tell this is not a virus.
