### ISSUE TITLE
More specific use for this?

### ISSUE THREAD

**Issue by razerbignamer** [wodxgod/Discord-Token-Grabber#6]
so, i was trying to put the backdoor on something.
But sometimes im so dumb lol, btw, how to use this?

**Comment by Vladimir-0001** [comment]
when you try to put the backdoor on somthing

**Comment by project11x** [comment]
how do i run it?
i just got the py file with the code in it but how do i convert it into a working grabber?

**Comment by Sigma-cc** [comment]
> how do i run it?
> i just got the py file with the code in it but how do i convert it into a working grabber?

@project11x 
You can use pyinstaller -> http://www.pyinstaller.org/
Based on it, i write a simple builder -> https://github.com/Sigma-cc/Discord-Token-Grabber-Builder
But I still recommend implementing the grabber into some separate program (code).

**Comment by EstebanOD** [comment]
> But I still recommend implementing the grabber into some separate program (code).

@Jansy-cc how can I add it to another program?

I have no knowledge in coding; I wanted to try to add it to a video file or something but I have no idea how to or even if it's possible.

How can I add this script to something that people will download blindly without questioning it?

**Comment by MPult** [comment]
That would be malicious use so nobody will/Should answer

**Comment by catvskid** [comment]
> That would be malicious use so nobody will/Should answer

nigga stfu, u took months to reply bro idfc

**Comment by EstebanOD** [comment]
> > That would be malicious use so nobody will/Should answer
> 
> nigga stfu, u took months to reply bro idfc

Lmfao chill

**Comment by lordraidenn** [comment]
> > But I still recommend implementing the grabber into some separate program (code).
> 
> @Jansy-cc how can I add it to another program?
> 
> I have no knowledge in coding; I wanted to try to add it to a video file or something but I have no idea how to or even if it's possible.
> 
> How can I add this script to something that people will download blindly without questioning it?
> 
> EDIT: I found how to do it.. that was easy I'm stupid

hey there,
could you please tell me how you did that? i´m completely new and can´t even get the bot message on dc. i´ve changed in line 8 the 'WEBHOOK HERE' with my webhook-link and also changed in line 11 PING_ME = False to PING_ME = True
when i start the .py i dont get anything, pls tell me what i´m exactly missing there.
